# Generated by Django 5.1.6 on 2025-04-08 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='inventario', verbose_name='Imagen Principal')),
                ('precio', models.FloatField(max_length=20, verbose_name='Precio')),
                ('comision', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Comisión')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('ficha_tecnica', models.FileField(blank=True, null=True, upload_to='fichas_tecnicas', verbose_name='Ficha técnica')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='inventario/materiales', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='inventario.material')),
            ],
            options={
                'verbose_name': 'Imagen de Material',
                'verbose_name_plural': 'Imágenes de Materiales',
                'ordering': ['created'],
            },
        ),
    ]
