# Generated by Django 5.1.6 on 2025-04-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='destacado',
            field=models.BooleanField(blank=True, default=False, verbose_name='Destacado'),
        ),
    ]
