# Generated by Django 5.1.7 on 2025-04-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_material_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
