"""
Django settings for gestores2 project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

from django.contrib.messages import constants as mensajes

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-yujkf=!kd56hv991ld4qv3717n-1q9ftigs$1r9=)vb5wkfmh+')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['ricardo397.pythonanywhere.com','127.0.0.1', 'localhost']  # For testing only - restrict in production


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gestorapp',
    'inventario',
    'carro',
    'autenticacion',
    'crispy_forms',
    'crispy_bootstrap4',
    'pedidos',
    'background_task',
    'rest_framework',  # Necesitarás añadir esto
    'corsheaders',     # Y esto
    'clientes'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'autenticacion.middleware.SingleSessionMiddleware',
    'autenticacion.middleware.PermissionsMiddleware',  # Nuevo middleware de permisos
]

ROOT_URLCONF = 'gestores2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'carro.context_processor.importe_total_carro',
            ],
        },
    },
]

# Update WSGI application path
WSGI_APPLICATION = 'gestores2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Database security settings
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'ATOMIC_REQUESTS': True,  # Ensure database transactions are atomic
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Password hashers configuration
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es'  # Spanish

TIME_ZONE = 'America/Havana'  # Cuba timezone

USE_I18N = True

USE_TZ = True

# Formato de fecha y hora
DATE_FORMAT = 'd/m/Y'  # DD/MM/AAAA
TIME_FORMAT = 'H:i'    # HH:MM (formato 24 horas)
DATETIME_FORMAT = 'd/m/Y H:i'
SHORT_DATE_FORMAT = 'd/m/Y'
SHORT_DATETIME_FORMAT = 'd/m/Y H:i'

# Usa formatos localizados
USE_L10N = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_TEMPLATE_PACK='bootstrap4'
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"
CRISPY_TEMPLATE_PACK = "bootstrap4"

MESSAGE_TAGS = {
    mensajes.ERROR: 'danger',
    mensajes.SUCCESS: 'success',
    mensajes.INFO: 'info',
    mensajes.WARNING: 'warning',
    mensajes.DEBUG: 'debug',
}

'''CELERY_BEAT_SCHEDULE = {
    'eliminar-pedidos-antiguos': {
        'task': 'pedidos.tasks.eliminar_pedidos_antiguos',
        'schedule': timedelta(hours=1),  # Ejecutar cada hora
    }
}'''

CORS_ALLOW_ALL_ORIGINS = False  # Solo para desarrollo

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

LOGIN_REDIRECT_URL = '/api/'

# Configuración de imágenes
IMAGE_QUALITY = 90
MAX_UPLOAD_SIZE = 5242880  # 5MB en bytes

# Configuración de caché para imágenes
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': str(BASE_DIR / 'django_cache'),
    }
}

CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 'http://127.0.0.1:8000', 'https://hecit.pythonanywhere.com']

# Configuraciones de Seguridad - DESACTIVADAS PARA DESARROLLO LOCAL
SECURE_SSL_REDIRECT = False  # Desactivado para desarrollo local
SECURE_HSTS_SECONDS = 0  # Desactivado para desarrollo local
SECURE_HSTS_INCLUDE_SUBDOMAINS = False  # Desactivado para desarrollo local
SECURE_HSTS_PRELOAD = False  # Desactivado para desarrollo local
SESSION_COOKIE_SECURE = False  # Desactivado para desarrollo local
CSRF_COOKIE_SECURE = False  # Desactivado para desarrollo local
SECURE_BROWSER_XSS_FILTER = True  # Mantenemos esta protección
SECURE_CONTENT_TYPE_NOSNIFF = True  # Mantenemos esta protección
X_FRAME_OPTIONS = 'DENY'  # Mantenemos esta protección

# Configuración CORS para desarrollo local
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "https://hecit.pythonanywhere.com",
    # Añade otros dominios permitidos si es necesario
]

CORS_ALLOW_ALL_ORIGINS = True  # Solo para desarrollo - CAMBIAR en producción

# Session security settings - Ajustadas para desarrollo local
SESSION_COOKIE_AGE = 3600  # 1 hora
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False  # Desactivado para desarrollo local
CSRF_COOKIE_SECURE = False  # Desactivado para desarrollo local