# Generated by Django 5.1.7 on 2025-04-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_eliminacion', models.IntegerField(default=24, help_text='Tiempo después del cual se eliminarán los pedidos no efectuados', verbose_name='Tiempo de eliminación (horas)')),
                ('activo', models.BooleanField(default=True, verbose_name='Eliminación automática activa')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Pedidos',
                'verbose_name_plural': 'Configuraciones de Pedidos',
            },
        ),
    ]
