# Generated by Django 5.1.7 on 2025-04-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_configuracionpedidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionpedidos',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Cancelación automática activa'),
        ),
        migrations.AlterField(
            model_name='configuracionpedidos',
            name='tiempo_eliminacion',
            field=models.IntegerField(default=24, help_text='Tiempo después del cual se cancelarán automáticamente los pedidos pendientes', verbose_name='Tiempo de cancelación (horas)'),
        ),
    ]
