# Generated by Django 5.1.6 on 2025-04-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_configuracionpedidos_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodetalle',
            name='en_oferta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='precio_regular',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio Regular'),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='precio_unitario',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio Unitario Usado'),
        ),
    ]
