# Generated by Django 5.1.7 on 2025-04-17 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedidodetalle_en_oferta_pedidodetalle_precio_regular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero_reactivacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedido_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactivaciones', to='pedidos.pedido'),
        ),
    ]
