# Generated by Django 5.1.7 on 2025-04-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_numero_reactivacion_pedido_pedido_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('efectuado', 'Efectuado'), ('cancelado', 'Cancelado'), ('reactivado', 'Reactivado'), ('reactivacion', 'Reactivación')], default='pendiente', max_length=20, verbose_name='Estado del pedido'),
        ),
    ]
